apiVersion: v1
kind: Namespace
metadata:
  name: letsencrypt-staging
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sample-app-tls
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-app-tls
  namespace: cert-manager
spec:
  dnsNames:
    - example.com
  secretName: sample-app-tls
  issuerRef:
    name: letsencrypt-staging
