apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-22T13:56:14Z"
  labels:
    app: sample-app
  name: sample-app
  namespace: default
  resourceVersion: "19063"
  uid: 2f9a56ef-1c51-4080-a5bd-cb3fd74750b7
spec:
  clusterIP: 10.108.106.205
  clusterIPs:
  - 10.108.106.205
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: sample-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
