name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2:$(echo $GITHUB_SHA | head -c7)
    - name: Build and push Docker image
      uses: docker/build-push-action@v4:$(echo $GITHUB_SHA | head -c7)
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sample-app:latest
    - name: Deploy to Kubernetes
      uses: ghostzero/kubectl@v1
      with:
        args: apply -f ./sample-app.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
