name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-docker-registry/sample-app:latest

    - name: Deploy to Kubernetes
      uses: ghostzero/kubectl@v1
      with:
        args: apply -f k8s/sample-app.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
